//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projet3.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Projet3.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le numéro de cellulaire entré n&apos;est pas valide.
        /// </summary>
        internal static string CelNonValide {
            get {
                return ResourceManager.GetString("CelNonValide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le code postal entré n&apos;est pas valide.
        /// </summary>
        internal static string CodePostalNonValide {
            get {
                return ResourceManager.GetString("CodePostalNonValide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;adresse courriel entrée n&apos;est pas valide.
        /// </summary>
        internal static string CourrielNonValide {
            get {
                return ResourceManager.GetString("CourrielNonValide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le mot de passe doit composer au moins 1 caractère.
        /// </summary>
        internal static string MotDePasseNonValide {
            get {
                return ResourceManager.GetString("MotDePasseNonValide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le numéro civique entré n&apos;est pas valide.
        /// </summary>
        internal static string NoCiviqueNonValide {
            get {
                return ResourceManager.GetString("NoCiviqueNonValide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veuillez entrer un numéro d&apos;employé valide.
        /// </summary>
        internal static string NoEmployeInvalide {
            get {
                return ResourceManager.GetString("NoEmployeInvalide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le nom entré n&apos;est pas valide.
        /// </summary>
        internal static string NomNonValide {
            get {
                return ResourceManager.GetString("NomNonValide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le prénom entré n&apos;est pas valide.
        /// </summary>
        internal static string PrenomNonValide {
            get {
                return ResourceManager.GetString("PrenomNonValide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veuillez selectionner la province de résidence de la personne.
        /// </summary>
        internal static string ProvinceNonSelectionne {
            get {
                return ResourceManager.GetString("ProvinceNonSelectionne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veuillez entrer une remarque.
        /// </summary>
        internal static string RemarquesNonValide {
            get {
                return ResourceManager.GetString("RemarquesNonValide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veuillez entrer le nom de la rue de résidence de la personne.
        /// </summary>
        internal static string RueNonValide {
            get {
                return ResourceManager.GetString("RueNonValide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le salaire entré n&apos;est pas valide.
        /// </summary>
        internal static string SalaireNonValide {
            get {
                return ResourceManager.GetString("SalaireNonValide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veuillez sélectionner le sexe de la personne.
        /// </summary>
        internal static string SexeNonSelectionne {
            get {
                return ResourceManager.GetString("SexeNonSelectionne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le numéro de téléphone entré n&apos;est pas valide.
        /// </summary>
        internal static string TelNonValide {
            get {
                return ResourceManager.GetString("TelNonValide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erreur.
        /// </summary>
        internal static string TitreErreur {
            get {
                return ResourceManager.GetString("TitreErreur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La combinaison nom d&apos;utilisateur/mot de passe ne correspond à aucun utilisateur enregistré.
        /// </summary>
        internal static string UtilisateurOuMotDePasseNonValide {
            get {
                return ResourceManager.GetString("UtilisateurOuMotDePasseNonValide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veuillez entrer le nom de la ville de résidence de la personne.
        /// </summary>
        internal static string VilleNonValide {
            get {
                return ResourceManager.GetString("VilleNonValide", resourceCulture);
            }
        }
    }
}
