//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.1008
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projet3.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Projet3.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à KelvinEstMexicain@gmail.com.
        /// </summary>
        internal static string AdresseGMail {
            get {
                return ResourceManager.GetString("AdresseGMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à smtp.gmail.com.
        /// </summary>
        internal static string AdresseSmtpGMail {
            get {
                return ResourceManager.GetString("AdresseSmtpGMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le numéro de cellulaire entré n&apos;est pas valide.
        /// </summary>
        internal static string CelNonValide {
            get {
                return ResourceManager.GetString("CelNonValide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Les changements ont été sauvegardés.
        /// </summary>
        internal static string ChangementsSauvegarde {
            get {
                return ResourceManager.GetString("ChangementsSauvegarde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ce client s&apos;est déjà réabonné cette année.
        /// </summary>
        internal static string ClientDejaReabonne {
            get {
                return ResourceManager.GetString("ClientDejaReabonne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le code postal entré n&apos;est pas valide.
        /// </summary>
        internal static string CodePostalNonValide {
            get {
                return ResourceManager.GetString("CodePostalNonValide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Il y a eu un conflit d&apos;accès concurrentiel, les modifications ne seront pas sauvegardées.
        /// </summary>
        internal static string ConflitAccesConcurrentiel {
            get {
                return ResourceManager.GetString("ConflitAccesConcurrentiel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à L&apos;adresse courriel entrée n&apos;est pas valide.
        /// </summary>
        internal static string CourrielNonValide {
            get {
                return ResourceManager.GetString("CourrielNonValide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Echec de l&apos;envoi du courriel:.
        /// </summary>
        internal static string EchecEnvoisCourriel {
            get {
                return ResourceManager.GetString("EchecEnvoisCourriel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à L&apos;enregistrement a réussi. Un courriel a été envoyé à l&apos;abonné..
        /// </summary>
        internal static string EnregistrementReussi {
            get {
                return ResourceManager.GetString("EnregistrementReussi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Il y a eu une erreur lors de la connexion à la base de donnée.
        /// </summary>
        internal static string ErreurBD {
            get {
                return ResourceManager.GetString("ErreurBD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Il y a eu une erreur lors de l&apos;enregistrement.
        /// </summary>
        internal static string ErreurEnregistrement {
            get {
                return ResourceManager.GetString("ErreurEnregistrement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Veuillez entrer un chiffre qui est plus grand que 0..
        /// </summary>
        internal static string MontantNonValide {
            get {
                return ResourceManager.GetString("MontantNonValide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à DavidEstPasMexicain.
        /// </summary>
        internal static string MotDePasseGMail {
            get {
                return ResourceManager.GetString("MotDePasseGMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le mot de passe doit être composé d&apos;au moins 1 caractère.
        /// </summary>
        internal static string MotDePasseNonValide {
            get {
                return ResourceManager.GetString("MotDePasseNonValide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le numéro civique entré n&apos;est pas valide.
        /// </summary>
        internal static string NoCiviqueNonValide {
            get {
                return ResourceManager.GetString("NoCiviqueNonValide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Veuillez entrer un numéro d&apos;employé valide.
        /// </summary>
        internal static string NoEmployeInvalide {
            get {
                return ResourceManager.GetString("NoEmployeInvalide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le nom entré n&apos;est pas valide.
        /// </summary>
        internal static string NomNonValide {
            get {
                return ResourceManager.GetString("NomNonValide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pour être de l&apos;âge d&apos;or, la personne doit être agée de 60 ans ou plus.
        /// </summary>
        internal static string PasAgeDor {
            get {
                return ResourceManager.GetString("PasAgeDor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le prénom entré n&apos;est pas valide.
        /// </summary>
        internal static string PrenomNonValide {
            get {
                return ResourceManager.GetString("PrenomNonValide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Veuillez selectionner la province de résidence de la personne.
        /// </summary>
        internal static string ProvinceNonSelectionne {
            get {
                return ResourceManager.GetString("ProvinceNonSelectionne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Veuillez entrer une remarque.
        /// </summary>
        internal static string RemarquesNonValide {
            get {
                return ResourceManager.GetString("RemarquesNonValide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Veuillez entrer le nom de la rue de résidence de la personne.
        /// </summary>
        internal static string RueNonValide {
            get {
                return ResourceManager.GetString("RueNonValide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le salaire entré n&apos;est pas valide.
        /// </summary>
        internal static string SalaireNonValide {
            get {
                return ResourceManager.GetString("SalaireNonValide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Veuillez sélectionner le sexe de la personne.
        /// </summary>
        internal static string SexeNonSelectionne {
            get {
                return ResourceManager.GetString("SexeNonSelectionne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Voici les informations de votre abonnement.
        /// </summary>
        internal static string SujetMailAbonnement {
            get {
                return ResourceManager.GetString("SujetMailAbonnement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Voici les informations de votre réabonnement.
        /// </summary>
        internal static string SujetMailReabonnement {
            get {
                return ResourceManager.GetString("SujetMailReabonnement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vous ne pouvez supprimer l&apos;administrateur.
        /// </summary>
        internal static string SupprimerAdmin {
            get {
                return ResourceManager.GetString("SupprimerAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vous ne pouvez supprimer un utilisateur qui offre des services.
        /// </summary>
        internal static string SupprimerAdminAvecService {
            get {
                return ResourceManager.GetString("SupprimerAdminAvecService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vous ne pouvez vous supprimer vous même.
        /// </summary>
        internal static string SupprimerSoisMeme {
            get {
                return ResourceManager.GetString("SupprimerSoisMeme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le numéro de téléphone entré n&apos;est pas valide.
        /// </summary>
        internal static string TelNonValide {
            get {
                return ResourceManager.GetString("TelNonValide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Abonnement du conjoint(e).
        /// </summary>
        internal static string TitreAbonnementConjoint {
            get {
                return ResourceManager.GetString("TitreAbonnementConjoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Abonnement d&apos;un enfant.
        /// </summary>
        internal static string TitreAbonnementEnfant {
            get {
                return ResourceManager.GetString("TitreAbonnementEnfant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erreur.
        /// </summary>
        internal static string TitreErreur {
            get {
                return ResourceManager.GetString("TitreErreur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Réabonné.
        /// </summary>
        internal static string TitreReabonne {
            get {
                return ResourceManager.GetString("TitreReabonne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Réussi.
        /// </summary>
        internal static string TitreReussi {
            get {
                return ResourceManager.GetString("TitreReussi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sauvegardé.
        /// </summary>
        internal static string TitreSauvegarde {
            get {
                return ResourceManager.GetString("TitreSauvegarde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Veuillez selectionner un type d&apos;abonnement.
        /// </summary>
        internal static string TypeAbonnementNonValide {
            get {
                return ResourceManager.GetString("TypeAbonnementNonValide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le type de service ne peut être vide..
        /// </summary>
        internal static string TypeService_Invalide {
            get {
                return ResourceManager.GetString("TypeService Invalide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La combinaison nom d&apos;utilisateur/mot de passe ne correspond à aucun utilisateur enregistré.
        /// </summary>
        internal static string UtilisateurOuMotDePasseNonValide {
            get {
                return ResourceManager.GetString("UtilisateurOuMotDePasseNonValide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à L&apos;utilisateur a été réabonné et un courriel de confirmation lui a été envoyé.
        /// </summary>
        internal static string UtilisateurReabonne {
            get {
                return ResourceManager.GetString("UtilisateurReabonne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Veuillez entrer le nom de la ville de résidence de la personne.
        /// </summary>
        internal static string VilleNonValide {
            get {
                return ResourceManager.GetString("VilleNonValide", resourceCulture);
            }
        }
    }
}
